### ISSUE TITLE
CherryOK Business Protocol: No CherryHelp if customer does not have monitoring service

### ISSUE THREAD

**Issue by cherrycherrywiki** [ThePi2K/CherryOK#12]
When executing CherryOK in business mode and the customer does not have our monitoring service, the CherryHelp should be installed as a substitute. This does not happen by default and leaves the device without remote desktop tools, which is
✨not good✨

**Comment by ThePi2K** [comment]
is this still an issue? @cherrycherrywiki

**Comment by ThePi2K** [comment]
TO TEST! @cherrycherrywiki
